on:
  schedule:
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python script
        run: python send_and_delete.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_TEXT: ${{ secrets.
          
